stages:
  - unittest
  - build
  - deploy
#
variables:
  LOCAL_REPO: "192.168.3.7:8081/fastapi_demo/"

Unittest:
  stage: unittest
  script:
    - make testcase
  tags:
    - py3

build:
  stage: build
  only:
    - master
    - /^feat.+$/
    - /^fix\/.+$/
  script:
    - cd $CI_PROJECT_DIR
    - docker build --pull -t ${LOCAL_REPO}/app:$CI_COMMIT_SHA -f ./cmd/${CMD_NAME}/Dockerfile .
    - docker push ${LOCAL_REPO}/app:$CI_COMMIT_SHA
  tags:
    - py3

deploy_prev_test_project:
  stage: deploy
  when: manual
  tags:
    - py3
  only:
    - master
  variables:
    ENV: staging-eks-1
    APP_NAME: test_project
    TAG: $CI_COMMIT_SHA
