app:
  env: dev
  version: v1
  machine_id: local
  sso_center: https://xxxx/

db:
  max_idle_conn: 10
  max_open_conn: 20
  log_mode: False

redis:
  key_pref: testProject
  max_open_conn: 100
  max_idle_conn: 100
  ssl: false


# mq producer consumer
user-service-producer:
  exchangeName: testproject.service
  durable: true
  kind: fanout
user-service-consumer:
  exchangeName: testproject.service
  queueName: social
  queueDurable: true #chi jiuhua
  exchangeDurable: true
  kind: fanout
  parallel: 4
  autoAck: false
  prefetch: 1
