mysql:
  host: 0.0.0.0
  port: 3306
  username: root
  password: root
  database: test_project

redis:
  host: 0.0.0.0
  port: 6379
  password: '000415'
  db: 0


rabbitmq:
  host: 0.0.0.0
  port: 5672
  username: guest
  password: guest


# product

# consumer